### ISSUE TITLE
An issue when using numbers with floating point.

### ISSUE THREAD

**Issue by ghost** [superblaubeere27/masxinlingvonta#1]
Example:
@Оutsource // used russian O letter to prevent github mentioning random user.
public static void main(String[] args) {
System.out.println(3.1f + 3.9f);
}

// error on compiling .dll: lld-link: undefined symbol: _fltused

**Comment by superblaubeere27** [comment]
Thanks for your report! I hopefully fixed this problem in a0cd9eaec36d1b36fa4ad1d1cb67c3a58fb0c035. From this update on, you will have to have Visual Studio with C++ Support installed. Please let me know if the fix works.

**Comment by ghost** [comment]
> Thanks for your report! I hopefully fixed this problem in [a0cd9ea](https://github.com/superblaubeere27/masxinlingvonta/commit/a0cd9eaec36d1b36fa4ad1d1cb67c3a58fb0c035). From this update on, you will have to have Visual Studio with C++ Support installed. Please let me know if the fix works.

Thank you! Works now.
