### ISSUE TITLE
About LoaderAdderPostprocessor postProcess void

### ISSUE THREAD

**Issue by nuym** [superblaubeere27/masxinlingvonta#11]
In LoaderAdderPostprocessor.java, I found a method to get the mainMethod and then add loadNatives This method does not work and does not report any error, I can't find this method in the obfuscated file.

**Comment by superblaubeere27** [comment]
The program should print something to stderr if no loader was injected (`https://github.com/superblaubeere27/masxinlingvonta/blob/master/masxinlingvonta-core/src/main/java/net/superblaubeere27/masxinlingvaj/postprocessor/LoaderAdderPostprocessor.java#L36C33-L36C58`), so there are three options: (1) the method went missing (2) another method was modified (3) the class did not run.

Can you specify the problem more precisely? Does the program run?
