### ISSUE TITLE
Unknown lifecycle phase ".platform=windows-x86_64"

### ISSUE THREAD

**Issue by BullyWiiPlaza** [superblaubeere27/masxinlingvonta#5]
I'm on Windows 10 64-bit and when I try to build this project, I get the following error:
```
[ERROR] Unknown lifecycle phase ".platform=windows-x86_64". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<
plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test
-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, pos
t-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```
The command I used was `mvn -Djavacpp.platform=windows-x86_64 clean package` according to the README. My `JAVA_HOME` points to Java 11. I have LLVM and the Windows C++ support installed.

Anything I did wrong or are the README build instructions incorrect? You're not providing a pre-built annoations JAR as it seems, otherwise I could use that and skip building this project.

**Comment by superblaubeere27** [comment]
Are you using CMD or PowerShell? I only tested this using CMD

**Comment by BullyWiiPlaza** [comment]
Okay, for some weird reason the project is compiling flawlessly now. Maybe my PC restart fixed it. I'm using CMD. Thanks for your reply anyway. 👍
